@startuml


class "Заказчик" as class1 {
    -ФИО: string
    -Идентификатор: string
    -Номер_телефона: int
    +Местоположение: array
    +Заказать_поездку_себе()
    +Заказать_поездку_другому()
    +Изменить_поездку()
    +Отказаться_от_поездки()
    +Оплатить_поездку()
}
class "Пассажир" as class2 {
    -ФИО: string
    -Идентификатор: string
    -Номер_телефона: int
    +Создать()
    +Удалить()
    +Редактировать()
}

class "Поездка" as class3 {
    +Идентификатор: string 
    +Дата_время_начала: datetime
    +Дата_время_окончания: datetime
    +Создать()
    +Редактировать()
    +Отменить()
} 

class "Маршрут" as class4 {
    +Идентификатор: string
    +Место_отправления: string
    +Место_назначения: string
    +Расстояние: float
    +Продолжительность: float
    +Создать()
    +Удалить()
    +Редактировать()
}

class "Водитель" as class5 {
    +ФИО: string
    +Идентификатор: string
    +Номер_телефона: int
    +Рейтинг: float
    +Местоположение: array
    +Добавить()
    +Удалить()
    +Редактировать()
}

class "Оплата" as class6 {
    +Идентификатор: string
    +Дата_время: datetime
    +Сумма: float
    +Статус: enum
    +Способ_оплаты: enum
    -Номер_карты: int
    +Создать()
}

class "Транспортное_средство" as class7{
    +Идентификатор: string 
    +Состояние: enum
    +Уровень_комфорта: enum
    +Цвет: enum
    +гос_номер: string
    +Детское_кресло: int
    +Добавить()
    +Удалить()
    +Редактировать()
}

class "Платежная_карта" as class8{
    +Идентификатор: string
    -Номер_карты: int
    +Добавить()
    +Удалить()
}

class1 "1  " <|-- "0...*" class2
class3 "0...*" o--  "1" class1
class3 "1    " *-- "1 " class4
class3 "0...*  " o-- "1 " class5
class3 "1" *-- "1 " class6
class3 "0...*" o-- "1 " class7
class1 "1" <-- "0...*      "class8
class6 "1...*"<-- "1" class8
class5 "1...* " <-- "1...* " class7

@enduml