@startuml

[*] --> Создание_заказа 

Создание_заказа :  Заказчик делает заказ,\n определяет параметры поездки
Создание_заказа --> Ожидание_подтверждения : Подтверждены\n параметры поездки

Ожидание_подтверждения : Cистема производит поиск свободного\n водителя. В этом состоянии заказ\n находится до тех пор, пока водитель\nне примет его
Ожидание_подтверждения --> [*] : Заказчик\n отменил заказ
Ожидание_подтверждения : \nЗаказчик может отменить заказ
Ожидание_подтверждения -> Водитель_найден : Водитель\n получил\nпредложение\nо заказе

Водитель_найден : Система Нашла свободного\n водителя, который готов\n принять заказ
Водитель_найден : \nЗаказчик может отменить заказ
Водитель_найден : \nВодитель может отменить заказ
Водитель_найден  --> [*] : Заказчик\n отменил заказ
Водитель_найден -> Подтверждение_водителя : Водитель подтвердил\nпринятие заказа.\nЕдет забирать пассажира
Водитель_найден --> Ожидание_подтверждения : Водитель\nотказался\n от заказа

Подтверждение_водителя : Водитель принимает заказ,\n и двигается к забору Пассажира 
Подтверждение_водителя : \nЗаказчик может отменить заказ
Подтверждение_водителя  -> [*] : Заказчик\n отменил заказ
Подтверждение_водителя -> В_пути : Водитель\n осуществляет поездку

В_пути : Водитель забрал Пассажира\nЗаказ находится в процессе\n выполнения, водитель движется\nк месту назначения.
В_пути -> Завершение_заказа : ТС прибыло\n на место назначения

Завершение_заказа : Водитель прибыл место\nи завершает заказ.\nЗаказ считается выполненным.
Завершение_заказа -> Оплата 

Оплата : Заказчик\n оплачивает заказ
Оплата -> Закрытие_заказа : Оплата исполнена

Закрытие_заказа : После оплаты\nзаказ закрывается,\nи система переводит его\nв архив
Закрытие_заказа --> [*]

@enduml