@startuml

()КлиентскийИнтерфейс 


package "Блог-платформа" {
[Аутентификация\n и авторизация\nOAuth2.0]  as Comp1
'Этот сервис отвечает за аутентификацию пользователей и управление их доступом к ресурсам платформы. Он может использовать протоколы OAuth или JWT для выдачи токенов доступа.

()ДоступыРоли -- Comp1 
()КлиентскийИнтерфейс -- Comp1 





[Пользователи] as Comp2
()ПользователиЛоги -- Comp2
'Этот сервис отвечает за управление учетными записями пользователей, их профилями, ролями и правами доступа.

[Контент] as Comp3
()УправлениеКонтентом -- Comp3
()КонтентЛоги -- Comp3
'Этот сервис отвечает за управление статьями, постами, комментариями и другим контентом блога. Он обеспечивает CRUD операции над контентом и его модерацию.

[Комментарии] as Comp4
()УправлениеКоммментариями -- Comp4
()КоммментарииЛоги -- Comp4

'Этот сервис специализируется на управлении комментариями к постам блога. Он обеспечивает добавление, редактирование и удаление комментариев, а также их модерацию.

[Подписки и уведомления] as Comp5
()УправлениеПодпискамиИУведомлениями -- Comp5
()ПодпискамиИУведомлениямиЛоги - Comp5
'Этот сервис отвечает за управление подписками пользователей на авторов, теги или конкретные посты, а также за отправку уведомлений о новом контенте или активности в блоге.

[Аналитики и мониторинг\nPrometheus] as Comp6
()Отчеты -- Comp6

'Этот сервис собирает и анализирует данные о активности пользователей на платформе, такие как количество посещений, просмотров и взаимодействий с контентом. Он также отвечает за мониторинг состояния микросервисов и обеспечение их доступности и производительности.

[Администрирование] as Comp7
'Этот сервис предоставляет интерфейс администратора для управления конфигурацией и мониторингом платформы, а также для выполнения операций администрирования, таких как управление пользователями и контентом, настройка безопасности и масштабируемости.


[Comp2] -----> [ДоступыРоли]
[Comp2] ...> [УправлениеКонтентом]
[Comp3] ..> [УправлениеКоммментариями]
[Comp3] ..> [УправлениеПодпискамиИУведомлениями]
[Comp6] --------> [ДоступыРоли]
[Comp6] --> [ПодпискамиИУведомлениямиЛоги]
[Comp6] --> [ПользователиЛоги]

[Comp6] --> [КоммментарииЛоги]
[Comp6] --> [КонтентЛоги]
[Comp7] --> [Отчеты]
[Comp7] --> [ДоступыРоли]
}

@enduml
