@startuml
actor   Клиент as S1
boundary "Пользовательский\n интерфейс банкомата (экран)" as S2
entity  "Хранилище банкнот в банкомате" as S3
entity "Комиссия за снятие" as S4
participant "Система Банка" as S5
database "Карточные счета клиентов" as S6
entity "Принтер чеков" as S7
participant "Сервис отправки чека на телефон" as S8

activate S1
' loop' Ввод и проверка суммы
    S1 -> S2 : Ввод суммы снятия наличных
    
    activate S2
    S2 -> S3 : Сумма снятия
    activate S3
           

        par Проверка наличия\n суммы купюр в АТМ
            S3 ->> S3 : Проверка наличия суммы
            S3 ->> S3 : Проверка наличия купюр            
        end
        alt Если купюры в наличии
            S3 -> S4 : Сумма снятия
            deactivate S3
            activate S4         
       
            S4 -> S4 : Расчет суммы комисии
            S4 -> S2 : Сумма комисии
            deactivate S4
            S2 -> S2 : Уведомление\nо размере комиссии

                alt Подтверждает\nсумму комиссии
                S1 -> S2 : Подтверждает согласие\n  с комиссией
                S2 -> S5 : Согласие на списание
                activate S5
                S5 -> S5 : Обработка информации\nПроведение транзации\n списания/выдачи средств
                S5 -> S6 : Запрос баланса\nДанные по транзакции
                activate S6
                    S6 -> S6 : Сохранение данных\n обновление баланса                    
                    alt Успешное списание    
                    S6 -> S5 : callback\nтранзакция проведена
                    deactivate S6
                    S5 -> S2 : Подтверждение успешного\n списания средств
                    deactivate S5
                    S2 -> S2 : Предложение распечатать\nчек, отказаться или\n отправить на телефон
                        alt Согласился распечатать
                        S2 -> S7 : Данные по операции 
                        activate S7
                        S7 -> S7 : Печать чека
                        else Отказался от чека                                                
                        else Согласился отправить\n чек на телефон
                        deactivate S7
                        S2 -> S8 : Данные по операции
                        activate S8                        
                        S8 -> S8 : Отправка чека на телефон                                   
                        end
                        deactivate S8
                    S2 -> S3 : Команда на выдачу средств
                    activate S3
                    S3 -> S3 : Выдача средств                             
                    S2 -> S2 : Уведомление забрать деньги    
                    |||
                    else Недостаточно средств на карте
                    activate S5
                    S5 -> S2 : Сообщение: недостаточно\n средств на карте
                    deactivate S5
                    |||
                    S2 -> S2 : Уведомление\n об отстутствии средств на карте\nПредложение поменять сумму
                        alt Если согласен\nизменить сумму
                        S1 -> S2 : Ввод суммы снятия наличных
                         |||
                        else Если отказался продолжения
                            S1 -> S2 : Отменяет ввод суммы
                            deactivate S2
                            destroy S1
                            destroy S2
                        end
                    end
                |||

                else Отказывается от операции
                S1 -> S2 : Отказывается
                destroy S1
                destroy S2
                end
            activate S3
        else Если отсутствует сумма в банкомате
                S3 -> S2 : Сообщение об отсутствии\n суммы/купюр
        activate S1
        activate S2
        deactivate S3
        S2 -> S2 : Уведомление об отсутствии\n  суммы/купюр.\n Предложение изменить сумму

            alt Если согласен\nизменить сумму
            S1 -> S2 : Ввод суммы снятия наличных
            |||

            else Если отказался продолжения
                S1 -> S2 : Отменяет ввод суммы
                deactivate S2
                destroy S1
                destroy S2
            end
           
        end   
' end



@enduml