@startuml
left to right direction
rectangle "Получение наличных в портативном банкомате с доставкой" {
    (Запросить сумму для снятия) as (UC1)
    (Узнать размер комиссии) as (UC2)
    (Узнать об отсутствии суммы в терминал\nи изменить/ввести иную сумму) as (UC2.1a)
    (Узнать об отсутствии купюр в терминале\nи  изменить/ввести иную сумму) as (UC2.1b)
    (Соглаcиться с размером комиссии) as (UC3)
    (Узнать об отсутствии\nдостаточной суммы на карте\nи изменить/ввести иную сумму) as (UC5.1)
    (Получить чек об операции) as (UC4)
    (Чек печатать/не печатать) as UC6

    note "или отправить на телефон" as N1
}
: Клиент : as 1
1 -> UC1 
1 --> UC2
UC2 .> UC3 : extends
1 --> UC4
UC1 <.. UC2.1a : extends
UC1 <.. UC2.1b : extends
UC1 <. UC5.1 : extends
UC4 .> UC6 : includes
UC4 .. N1
@enduml